### PR TITLE
Skip tests if slacker is not available

### PR DESCRIPTION
**Pull request by hansmosh**

### CODE REVIEW

**Comment by mattdodge** [comment]
I know we've been doing this in other tests, but I'd actually rather see us try and import `slacker` in the try block rather than just importing the block. I know if slacker is not available the block will fail to import too, but the block will also fail to import if it has a syntax error or something similar. Then the test would get skipped and we wouldn't be aware.

**Comment by hansmosh** [comment]
@mattdodge Yeah, I was thinking about that too when I was doing this. I'm glad you said something.

**Comment by hansmosh** [comment]
What about something like this? What is the expected result if the block file cannot be imported?

```slacker_available = True
try:
    from slacker import Slacker
except:
    slacker_available = False

try:
    from ..slack_block import Slack
except:
    # Allow tests to fails if the block cannot be imported
    pass```

**Comment by mattdodge** [comment]
Yeah, I'm assuming if the block fails to import and there is no try/except then the test file just doesn't get loaded and thus no tests run or fail. If that's the case, then I think our options are:
1. Ignore the bad import - let the test reference a class that doesn't exist (the one you laid out)
2. Perform the block import inside the test

**Pull request merged**
